version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:35"
      timezone: "Asia/Ho_Chi_Minh"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "DEV-353: "
      include: "scope"
