version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:20"
      timezone: "Asia/Ho_Chi_Minh"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "DEV-353: "
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:20"
      timezone: "Asia/Ho_Chi_Minh"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "DEV-353: "
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:20"
      timezone: "Asia/Ho_Chi_Minh"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "DEV-353: "
      include: "scope"
