name: Create Jira PBI for Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract PR Information
        id: pr_info
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Search for existing Jira PBI
        id: search_issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        run: |
          echo "PR_TITLE: '$PR_TITLE'"
          if [[ "$PR_TITLE" =~ (DEV-[0-9]{3,4}:?\ ?\(deps\):?\ )?Bump\ ([a-zA-Z0-9_/-]+)\ from\ ([0-9]+\.[0-9]+\.[0-9]+)\ to\ ([0-9]+\.[0-9]+\.[0-9]+)\ in\ (.*) ]]; then
            echo "Match found!"
            LIBRARY_NAME="${BASH_REMATCH[2]}"
            OLD_VERSION="${BASH_REMATCH[3]}"
            NEW_VERSION="${BASH_REMATCH[4]}"
            
            echo "LIBRARY_NAME: $LIBRARY_NAME"
            echo "OLD_VERSION: $OLD_VERSION"
            echo "NEW_VERSION: $NEW_VERSION"

            # log library name
            echo "LIBRARY_NAME=$LIBRARY_NAME" >> $GITHUB_ENV

            JQL_QUERY="project=$JIRA_PROJECT_KEY AND summary~\"Bump $LIBRARY_NAME from\""
            ENCODED_JQL=$(echo "$JQL_QUERY" | jq -sRr @uri)

            echo "JQL_QUERY=$JQL_QUERY"
            echo "ENCODED_JQL=$ENCODED_JQL"

            EXISTING_ISSUE_KEY=$(curl -s -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
              -H "Content-Type: application/json" \
              "$JIRA_BASE_URL/rest/api/3/search?jql=$ENCODED_JQL" | jq -r '.issues[0]?.key // ""')

            echo $EXISTING_ISSUE_KEY
            
            echo "EXISTING_ISSUE_KEY=$EXISTING_ISSUE_KEY" >> $GITHUB_ENV
            echo "LIBRARY_NAME=$LIBRARY_NAME" >> $GITHUB_ENV
            echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          fi

      - name: Create or Update Jira Issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          LIBRARY_NAME="${{ env.LIBRARY_NAME }}"
          OLD_VERSION="${{ env.OLD_VERSION }}"
          NEW_VERSION="${{ env.NEW_VERSION }}"
          EXISTING_ISSUE_KEY="${{ env.EXISTING_ISSUE_KEY }}"

          JIRA_DESCRIPTION=$(cat <<EOF
          {
            "type": "doc",
            "version": 1,
            "content": [
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "Pull Request Created by $PR_AUTHOR"
                  }
                ]
              },
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "Title: $PR_TITLE"
                  }
                ]
              },
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "Description: abcde"
                  }
                ]
              },
              {
                "type": "paragraph",
                "content": [
                  {
                    "type": "text",
                    "text": "Link: "
                  },
                  {
                    "type": "text",
                    "text": "$PR_URL",
                    "marks": [
                      {
                        "type": "link",
                        "attrs": {
                          "href": "$PR_URL"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )

          if [ -n "$EXISTING_ISSUE_KEY" ]; then
            echo "Updating existing Jira Issue: $EXISTING_ISSUE_KEY"
            UPDATED_TITLE="Bump $LIBRARY_NAME from ${OLD_VERSION} to ${NEW_VERSION}"

            curl -s -X PUT \
              -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{\"fields\": {\"summary\": \"$UPDATED_TITLE\", \"description\": $JIRA_DESCRIPTION}}" \
              "$JIRA_BASE_URL/rest/api/3/issue/$EXISTING_ISSUE_KEY"
          else
            echo "Creating a new Jira Issue"
            curl -s -X POST \
              -H "Content-Type: application/json" \
              -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
              --data '{
                "fields": {
                  "project": {
                    "key": "'"$JIRA_PROJECT_KEY"'"
                  },
                  "summary": "'"$PR_TITLE"'",
                  "description": '"$JIRA_DESCRIPTION"',
                  "issuetype": {
                    "name": "Story"
                  }
                }
              }' \
              "$JIRA_BASE_URL/rest/api/3/issue/"
          fi